project:
  type: website

website:
  title: "Google Summer of Code 2024 | NUMFOCUS | QuTiP"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gadhvirushiraj
format:
  html:
    theme: cosmo
    css: styles.css